// vue/v-view/components/layout/virtualFallsList/index.vue
<template>
  <r-scroll-virtual-falls-list :ref="onRef" v-model="list" @renderList="onRenderList" />
</template>

<script setup lang="jsx">
import { render, defineComponent, computed, toRaw ,onMounted} from "vue";

const slots = defineSlots();
const emit = defineEmits(["update:modelValue"]);
const props = defineProps({
  modelValue: { type: Array, default: () => [] },
  keyExtractor: { type: Function, default: (val) => val.item },
  listHook: { type: Object, default: () => ({}) },
});

const list = computed({
  set(val) {
    if (props.listHook.list) return props.listHook.list = val;
    emit("update:modelValue", val);
  },
  get() {
    if (props.listHook.list) return props.listHook.list;
    return toRaw(props.modelValue);
  },
});

const refList = computed(()=>{
  if (props.listHook.list) return props.listHook.list;
  return props.modelValue;
})

const Item = defineComponent({
  props: {
    event: Object,
    slots: Object,
  },
  setup(props) {
    onMounted(()=>{
    })
    return () => {
      return (
        <div class="r-scroll-virtual-falls-list-item-content">
          {props?.slots?.default?.(props.event)}
        </div>
      );
    };
  },
});

function onRef(el) {
  if (el) el.keyExtractor = props.keyExtractor;
}

function onRenderList(event) {
  event.item = refList.value[event.index];
  render(
    <Item
      event={event}
      slots={slots}
      key={props.keyExtractor(event)}
      data-key={props.keyExtractor(event)}
    ></Item>,
    event.ele,
  );
}
</script>

<style>
</style>

// react/r-doc/src/r-view/components/virtualFallsList/index.jsx
import ReactDOM from "react-dom/client";
import { useMemo } from "react";

export function RRVirtualFallsList(props) {
  let fn = (val) => val.item;

  function onRef(el) {
    if (!el) return;
    el.keyExtractor = props.keyExtractor || fn;
  }

  function onRenderList(event) {
    if (!event.ele._reactRoot) event.ele._reactRoot = ReactDOM.createRoot(event.ele);
    event.ele._reactRoot.render(
      <Item
        list={props.value}
        index={event.index}
        item={event.item}
        event={event}
        child={props.children}
      ></Item>,
    );
  }

  return <r-scroll-virtual-falls-list ref={onRef} value={props.value} onrenderList={onRenderList} />;
}

function Item(props) {
  const data = useMemo(() => {
    if (props.item.__isProxy) return props.item;
    props.item.__isProxy = true;
    const proxy = new Proxy(props.item, {
      set: (obj, prop, value) => {
        obj[prop] = value;
        props.event?.target?.$$?.layout?.();
        return true;
      },
    });
    props.list[props.index] = proxy;
    return proxy;
  }, []);

  const args = { ...props.event, data, item: data };

  return <div className="r-scroll-virtual-grid-list-item-content">{props?.child?.(args)}</div>;
}
