// vue/v-doc/src/views/hooks/radio.vue
<template>
  <div class="hooks-radio">
    <div>
      <button @click="radioList.updateSelect(radioList.list[9])">updateSelect</button>
      <button @click="radioList.updateValue(++radioList.value)">updateValue</button>
      <button @click="radioList.updateLabel(`label-${3}`)">updateLabel</button>
      <button @click="radioList.updateIndex(--radioList.index)">updateIndex</button>
      <button @click="updateList">updateList</button>
    </div>
    <div>
      <div> value: {{ radioList.value }}</div>
      <div> label: {{ radioList.label }}</div>
      <div> index: {{ radioList.index }}</div>
      <div> select: {{ radioList.select }}</div>
    </div>
    <ElTable :data="radioList.list">
      <ElTableColumn width="80">
        <template #default="{ row }">
          <ElButton size="small" :type="radioList.same(row) ? 'primary' : ''" @click="radioList.onSelect(row)">{{
            row.value }}
          </ElButton>
        </template>
      </ElTableColumn>
      <ElTableColumn prop="value" label="value"></ElTableColumn>
      <ElTableColumn prop="label" label="label"></ElTableColumn>
    </ElTable>
  </div>
</template>
<script setup>
import { arrayLoopMap } from '@rainbow_ljy/rainbow-js'
import { useListRadio } from '@rainbow_ljy/v-hooks'
import { computed, onMounted, ref } from 'vue'
import { ElTable, ElTableColumn, ElButton } from "element-plus"

const radioList = useListRadio({
  value: 8,
  list: arrayLoopMap(30, (value) => ({ value, label: `label-${value}` }))
})

function updateList() {
  radioList.updateList(arrayLoopMap(50, (value) => ({ value, label: `label-*-${value}` })))
  console.log(radioList)
}

</script>

// react/r-doc/src/pages/hooks/list/radio.js
import { useState, useMemo, useRef, useEffect } from "react";
import { useListRadio } from "@rainbow_ljy/r-hooks";
import { arrayLoopMap } from "@rainbow_ljy/rainbow-js";
import "./radio.css";

let testList = arrayLoopMap(1000000, (i) => ({ value: i, label: i, i, o: i, p: { i } }));

function App() {
  const listRadio = useListRadio({ list: arrayLoopMap(10, (i) => ({ value: i, label: i })) });
  const [val, setVal] = useState(0);

  // console.log(listRadio);
  async function click(item, index) {
    listRadio.onSelect(item, index);
    console.log(listRadio.value);
    await setVal(listRadio.value);
    console.log(val);
  }

  function push() {
    const s = Date.now();
    testList.push({ value: 111, label: 1111 });
    const e = Date.now();
    console.log(e - s);
  }

  function copy() {
    const s = Date.now();
    testList = [...testList, { value: 111, label: 1111 }];
    const e = Date.now();
    console.log(e - s);
  }

  return (
    <div className="hooks-list-radio">
      <button onClick={push}>push</button>
      <button onClick={copy}>copy</button>
      <div> hooks-list-radio</div>
      <div>
        {listRadio.list.map((el, index) => (
          <div
            className={`${listRadio.same(el, index) && "item-activite"}`}
            onClick={() => click(el, index)}
            key={el.value}
          >
            value {el.value} label {el.label}
          </div>
        ))}
      </div>
    </div>
  );
}

export default App;
